### ISSUE TITLE
OpenCV Error: Failed Assertion

### ISSUE THREAD

**Issue by teeple31** [sean-obrien/rpotter#2]
Receiving the following error: OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8000
Traceback (most recent call last):
  File "/home/pi/rpotter.py", line 138, in FindWand
    old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
cv2.error: /home/pi/opencv-3.1.0/modules/imgproc/src/color.cpp:8000: error: (-215) scn == 3 || scn == 4 in function cvtColor

Using the Pi NoIR.  Still searching for a solution.

**Comment by sean-obrien** [comment]
Are you running this under a virtual environment?  If you try running it
outside of a virtual environment does the error change?
ᐧ

**Comment by teeple31** [comment]
I am running in the virtual environment.  
I just tried outside of the virtual enviroment and now get a different error:

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
AttributeError: 'module' object has no attribute 'VisibleDeprecationWarning'

**Comment by sean-obrien** [comment]
Can you check your numpy version both inside and outside the virtual environment?

`python -c "import numpy; print numpy.__version__"`

**Comment by hebertg626** [comment]
I am also having the same issue as TEEPLE31. And I am also in virtual environment when trying. I will also check my numpy versions.

**Comment by teeple31** [comment]
I have 1.8.2 in both environments

**Comment by hebertg626** [comment]
1.12.0 in both.

**Comment by hebertg626** [comment]
Initializing point tracking
START switch_pin ON for pre-video test
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8000
Error: /home/pi/opencv-3.1.0/modules/imgproc/src/color.cpp:8000: error: (-215) scn == 3 || scn == 4 in function cvtColor

START incendio_pin ON and set switch off if video is running
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8000
No points found
Tracking Error: <type 'exceptions.NameError'>

(Raspberry Potter:1189): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(Raspberry Potter:1189): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Tracking Error: <type 'exceptions.NameError'>

**Comment by sean-obrien** [comment]
Ok - I'm rebuilding so I can dig into this...  right now I'm thinking this is related to the virtual environment and the OpenCV python bindings...

**Comment by hebertg626** [comment]
Thanks so much for the help.

**Comment by teeple31** [comment]
Everything I am reading is that OpenCV and PiCamera do not play well together.

**Comment by sean-obrien** [comment]
Something to try...

What version do you get when you run this outside the virtual env :

$ python
>>> import cv2
>>> cv2.__version__


ᐧ

**Comment by teeple31** [comment]
3.1 

--- Just remembered to check my python instance outside of the virtual env. 

Outside of virtual env:
$ python 3.4
>>import cv2
ImportError: No module named 'cv2'

---
$  python
>>import cv2
>>cv2.__version__
3.1

Inside virtual env:
$ python #python3.4

**Comment by hebertg626** [comment]
Import error no module named cv2.

**Comment by teeple31** [comment]
Problem solved for me.  Need to make sure I am running python2.7 in virtual env.

**Comment by hebertg626** [comment]
I am running 2.7.9 in both environments. Still have the problem though.

**Comment by hebertg626** [comment]
pi@raspberrypi:~ $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cv2
>>> 
[1]+  Stopped                 python
pi@raspberrypi:~ $ source ~/.profile
pi@raspberrypi:~ $ workon cv
(cv) pi@raspberrypi:~ $ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by teeple31** [comment]
Try:
$ sudo modprobe bcm2835-v4l2

**Comment by teeple31** [comment]
Meant to say:

$ source ~/.profile
$ workon cv
---assuming you are now in virtual env---
$ sudo pigpiod 
$ sudo modprobe bcm2835-v4l2
$ python2.7 rpotter.py

**Comment by hebertg626** [comment]
Yah buddy. You the man. Thanks so much for the help.

**Comment by shaynakapadia** [comment]
I am also getting a similar error.
Initializing point tracking
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.2.0/modules/imgproc/src/color.cpp, line 9748
Error: /home/pi/opencv-3.2.0/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cvtColor

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.2.0/modules/imgproc/src/color.cpp, line 9748
Traceback (most recent call last):
  File "rpotter.py", line 204, in <module>
    TrackWand()            
  File "rpotter.py", line 133, in TrackWand
    old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)
cv2.error: /home/pi/opencv-3.2.0/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cvtColor


sudo modprobe bcm2835-v4l2 fixed the first error, but I am not sure what to do about the 2nd error.

Anyone have any other ideas on how to fix it?

**Comment by teeple31** [comment]
What version of python do you have installed for the VM?

**Comment by shaynakapadia** [comment]
Python 2.7
Is it a problem with the version?

**Comment by bkirchman** [comment]
Anyone figure out this issue, same as sallyliest over here

**Comment by shaynakapadia** [comment]
A friend of mine figured it out and we got it to work. 
I just had to comment out line 250: cam.release()  
I also did what teeple3 said to do.

Also make sure you use the code that's in the ollivanderslamp folder. 

I ran into a couple other issues with linking the python modules so if you had a problem with that just lmk.

**Comment by jcfitzg** [comment]
I've been working on this damn lamp for so long, and have finally gotten far enough to even understand how to follow your instructions.  I have just gotten picture and tracking marks up on the pi via ssh and and pretty proud of myself, but of course I could have done none of it without you sharing your knowledge and experience.  Thanks to you, my daughter will have her harry potter lamp under the tree this xmas.
